default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { '5432' } %>

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: postgres

production:
  <<: *default
  database: myapp_production